admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_new:
    path:     /new
    defaults: { _controller: AdminBundle:Default:admin }

gestor:usuarios:
    path:     /gestor
    defaults: { _controller: AdminBundle:Default:getAll }

button_action_route:
    path:     /gestor/quitarRol
    defaults: { _controller: AdminBundle:Default:quitarRoles }
