# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        gestorBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
      gestor_fct_bd:
            entity:
                class: gestorBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        usuarios:
            pattern: ^/
            anonymous: ~
            provider: gestor_fct_bd
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path:   /logout
                target: /login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
      - {path: ^/login,roles: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/registro,roles: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/api,roles: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/config,roles: ROLE_SUPER_ADMIN}
      - {path: ^/admin,roles: ROLE_ADMIN}
      - {path: ^/,roles: ROLE_USER}
