<?php

namespace gestorBundle\Repository;

/**
 * ConfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfRepository extends \Doctrine\ORM\EntityRepository
{
}
