gestor_homepage:
    path:     /
    defaults: { _controller: gestorBundle:Empresa:all}

all_empresa:
    path:     /empresa/all
    defaults: { _controller: gestorBundle:Empresa:all}

nueva_empresa:
    path:     /empresa/new
    defaults: { _controller: gestorBundle:Empresa:new}

all_alumno:
    path:     /alumno/all
    defaults: { _controller: gestorBundle:Alumno:all}

api_empresas_get:
    path:     /api/empresas
    defaults: { _controller: gestorBundle:Api:empresasGet }
    methods: [GET]

api_empresas_post:
    path:     /api/empresas
    defaults: { _controller: gestorBundle:Api:empresasPost }
    methods: [POST]

all_profesores:
    path:     /profesores/all
    defaults: { _controller: gestorBundle:Profesores:all }

nuevo_profesor:
    path:     /profesores/new
    defaults: { _controller: gestorBundle:Profesores:nuevoProfesor}

profesores_get:
    path:     /api/profesores
    defaults: { _controller: gestorBundle:Api:profesoresGet }
    methods: [GET]

nuevo_registro:
    path:     /registro
    defaults: { _controller: gestorBundle:Registro:registro }

login:
    path:     /login
    defaults: { _controller: gestorBundle:Registro:login }
